name: JS Code Review and Test

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
  pull_request_review_comment:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

jobs:
  review-code:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repo
        uses: actions/checkout@v2

      # Use your private ai-pr-reviewer action
      - name: AI PR Reviewer
        uses: octafrica/code-review-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.AI_REVIEW_PAT_REPO }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          debug: false
          review_simple_changes: false
          review_comment_lgtm: false
